services:
  catalogdb:
    image: postgres

  catalog.api:
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogdb
    ports:
      - "8080:8080"   # Maps container port 8080 to host port 8080
      - "8081:8081"   # Maps container port 8081 to host port 8081 

volumes:
  postgres_catalog: